### ISSUE TITLE
Breaking changes in Vite

### ISSUE THREAD

**Issue by JacobMGEvans** [iFaxity/vite-plugin-istanbul#2] opened 2021-03-19 21:34 UTC
Seems to be breaking with a recent version of Vite 2.1.2

reverting Vite back to 2.0.1 fixed this fatal error
```shell
4:29:23 PM [vite] Internal server error: **removedSystemPathing**/src/components/App.tsx: don't know how to turn this value into a node
[0]   Plugin: vite:istanbul
[0]   File: **removedSystemPathing**/src/components/App.tsx
[0]       at valueToNode (**removedSystemPathing**/node_modules/@babel/types/lib/converters/valueToNode.js:90:9)
```

**Comment by iFaxity** [comment] 2021-03-24 18:07
Hello @JacobMGEvans, do you have a way to reproduce this? Seems hard to debug due to the ambiguous error message.

I'm thinking that it is in fact a syntax error from a library file within a babel utility function, could be because of some new syntax babel doesn't support out of the box. Or something babel supports in a more recent version.

**Comment by iFaxity** [comment] 2021-03-25 16:50
Upon further analysis this might be due to a mismatch between babels source mapping and the source mapping returned from Vite. As Michael described in this issue #1.

> A few issues I'm having:
> 
> 1. Looks like Babel's `transformSync` expects `inputSourceMap` to be a plain object, while `this.getCombinedSourcemap()` yields a `SourceMap` (I think? It outputs `SourceMap { ... }` to the console).
> 
> Error I was getting:
> 
> ```
> 4:22:39 PM [vite] Internal server error: don't know how to turn this value into a node
>   Plugin: vite:istanbul
>   File: /path/to/project/web/src/main.js
>   Error: don't know how to turn this value into a node
>       at valueToNode (/path/to/project/web/node_modules/@babel/types/lib/converters/valueToNode.js:90:9)
>       at Object.valueToNode (/path/to/project/web/node_modules/@babel/types/lib/converters/valueToNode.js:84:58)
>       at Object.exit (/path/to/project/web/node_modules/istanbul-lib-instrument/dist/visitor.js:641:30)
>       at PluginPass.exit (/path/to/project/web/node_modules/babel-plugin-istanbul/lib/index.js:158:38)
>       at newFn (/path/to/project/web/node_modules/@babel/traverse/lib/visitors.js:175:21)
>       at NodePath._call (/path/to/project/web/node_modules/@babel/traverse/lib/path/context.js:55:20)
>       at NodePath.call (/path/to/project/web/node_modules/@babel/traverse/lib/path/context.js:42:17)
>       at NodePath.visit (/path/to/project/web/node_modules/@babel/traverse/lib/path/context.js:101:8)
>       at TraversalContext.visitQueue (/path/to/project/web/node_modules/@babel/traverse/lib/context.js:115:16)
>       at TraversalContext.visitSingle (/path/to/project/web/node_modules/@babel/traverse/lib/context.js:84:19)
> ```

**Comment by iFaxity** [comment] 2021-03-25 16:51
I will push out a patch for this later today after I've reproduced the error first.

**Comment by iFaxity** [comment] 2021-03-25 21:32
Version 2.1.0 should fix it, can you verify it is working on your end as well so this can be marked as resolved?

**Comment by JacobMGEvans** [comment] 2021-03-26 15:41
I cannot, the project is Open Source I was just helping on something.

**Comment by JacobMGEvans** [comment] 2021-03-26 15:42
@HorusGoul if you are interested in trying the update, it looks like it should work now in your project.

**Comment by HorusGoul** [comment] 2021-03-28 23:07
I upgraded the package, it seems to be solved :tada: 

Thank you!

**Closed** 2021-06-03 08:47 UTC

**Comment by belwalshubham** [comment] 2022-12-23 07:34
hey , I got this error after integrate cypress code coverage in nuxt , 
[Vue warn]: Hydration node mismatch:
- Client vnode:..
can anyone help me on this ?

**Comment by iFaxity** [comment] 2022-12-23 16:47
Hi @belwalshubham, please make a new issue instead of commenting on a closed issue.

Also provide more information or a repository where the error can be reproduced
