### ISSUE TITLE
After integrating Cypress code coverage into Nuxt3, the app is not working properly.

### ISSUE THREAD

**Issue by belwalshubham** [iFaxity/vite-plugin-istanbul#60] opened 2022-12-24 06:02 UTC
I'm using the Vite Istanbul plugin to integrate cypress code coverage into my nuxt3 app. I'm getting the code coverage report, but my Nuxt3 app is not being compiled and is not functioning properly.
In our most recent version, we have the following code inside the Vite-Plugin-Istanbul folder:
```
transform(srcCode, id, options) {
      if (!enabled || options?.ssr || id.startsWith(MODULE_PREFIX) || id.startsWith(NULL_STRING)) {
        return;
      }
      if (testExclude.shouldInstrument(id)) {
        const sourceMap = sanitizeSourceMap(this.getCombinedSourcemap());
        const code = instrumenter.instrumentSync(srcCode, id, sourceMap);
        const map = instrumenter.lastSourceMap();
        return { code, map };
      }
    }
```
 Though I'm getting options.ssr value as both true & false for different files, when I run npm run dev, my app does not run properly, and an error message appears on the console, as shown in the screenshot below.
 
 ![error code coverage](https://user-images.githubusercontent.com/61574835/209423645-d08b6c9f-3e3c-42e1-b2df-9b33e907f209.PNG)

**Comment by iFaxity** [comment] 2022-12-24 16:31
Hi @belwalshubham, thanks for the issue.

I will look into reproducing the issue and find out why this is the case.

It might be that the server rendered code is still transformed in some way.
Or maybe the hydration is somehow transformed in some way.

If you could provide a reproduction for the problem this would speed up the process.
I'll see what i can do.

**Comment by belwalshubham** [comment] 2022-12-25 05:42
@iFaxity  Thanks for the response. Here are my steps. 
**Nuxt3 Vite support for Cypress coverage instrumentation**

I was trying to instrument the project code using the vite-plugin-istanbul npm package.

Inside the package.json, here are my package dependencies.
```
"@cypress/code-coverage": "^3.10.0",
"vite-plugin-istanbul": "^3.0.4",
```
Here's my nuxt.config.ts after installing the vite-plugin-Istanbul package:
```
vite: {
  vue: {
    template: {
      transformAssetUrls: true
    }
  },
  plugins: [
    istanbul({
      exclude: ['node_modules', 'test/', 'coverage/'],
      extension: [ '.js', '.ts', '.vue' ],
      cypress: true
    }),
  ]
},
```
Here is my cypress/support/e2e.ts file.
```
import '@cypress/code-coverage/support'
```
Here is my cypress.config.ts file.
```
import { defineConfig } from "cypress"
export default defineConfig({
  projectId: "x83arq", // TODO: hide this
  e2e: {
    baseUrl: "http://localhost:3000",
    setupNodeEvents(on, config) {
      require("@cypress/code-coverage/task")(on, config)
      return config
    }
  }
})
```
After running npm run dev, my UI interface crashed and was not getting complied properly. and an error message appears on the console, as shown in the screenshot above.

![error code coverage](https://user-images.githubusercontent.com/61574835/209457928-86500eab-4e5b-4d20-9207-3ea4ffe193c7.PNG)

However, when I run npx Cypress open, it displays my Cypress code coverage report after the test is completed, but the main issue is that my UI is not functioning and is not being compiled properly.

**Comment by iFaxity** [comment] 2022-12-26 12:24
@belwalshubham Thanks for the detailed repro and the repro code. This will help me look into the issue. Big thanks ☺️👍.

I'll try to look into it before new years.

**Comment by belwalshubham** [comment] 2022-12-27 05:15
okay @iFaxity  let me know if you get something related to this issue .

**Comment by belwalshubham** [comment] 2022-12-30 05:22
hey @iFaxity  any update on this issue ?

**Comment by iFaxity** [comment] 2022-12-30 17:24
Hi, I've setup the and the app seems to be working (have some errors as I cannot setup the Prisma database. However the app loads the login view and that I can view at least.

Debugging these sorts of issues are tricky as the code that is produced is sometimes vastly different. As Istanbul transforms a lot of the code to generate coverage. However the code seems to be entirely different with some of the imports. 

Without the istanbul plugin the application loads all the pages/components by importing them directly.
However when the plugin is enabled the pages gets imported using resolveComponent from Vue.

Seems really strange how the outcome of the code is this different.
I will dig around some more see what code is slotted into Istanbul and what comes out. Maybe the istanbul plugin somehow runs before Vue/Nuxt's plugins and this is why this happens.
But havn't debugged this sort of issue before, so I will try to do my best.

Image 1, without Istanbul plugin
![image](https://user-images.githubusercontent.com/9090703/210096733-0444a5a2-9819-45c9-a13e-909ca7a1a653.png)

Image 2, with istanbul plugin
![image](https://user-images.githubusercontent.com/9090703/210096765-5087e92d-d9e8-49bd-88b4-8d8898031d25.png)

**Comment by belwalshubham** [comment] 2023-01-02 06:16
hey @iFaxity  thanks for your response , In my case, I'm unable to login because my entire login page is not rendered, leaving a blank screen, and this error appears on my screen, as shown in the screenshot below.. I believe you're correct; perhaps the Istanbul plugin runs before Vue/plugins Nuxt's, which is why this occurs.
![issue error](https://user-images.githubusercontent.com/61574835/210199758-ac317548-f47f-4d21-96f9-41ffbfd78abc.PNG)

**Comment by belwalshubham** [comment] 2023-01-02 06:18
hey @iFaxity please let me know if you get anything on this .

**Comment by iFaxity** [comment] 2023-01-02 23:23
Hello, I've managed to hopefully find a fix for this now.

By telling the istanbul instrumenter to not compress the code it seems to be working, as the imports are not squashed together with app.vue which fixes the issue.

I will publish a fix within a day for this, just have to run some tests first before I push anything.

**Comment by iFaxity** [comment] 2023-01-03 00:18
Please try the fix by using the @next tag when installing the package.

`npm i --save-dev vite-plugin-istanbul@next`

**Comment by belwalshubham** [comment] 2023-01-03 10:56
hey @iFaxity, thank you, the problem has been resolved

**Comment by iFaxity** [comment] 2023-01-03 15:55
@belwalshubham. Great!

I will try to get it out as a 4.0.0 release soon.
As for now its only in a RC release.

**Closed by iFaxity** 2023-01-03 15:55 UTC
Labels: released on @next
