### ISSUE TITLE
bug: Vue3 coverage incorrect

### ISSUE THREAD

**Issue by songjiachao** [iFaxity/vite-plugin-istanbul#14] opened 2022-01-28 03:21 UTC
![image](https://user-images.githubusercontent.com/70792885/151481608-983145d6-cf52-4a28-9360-25cdbc60d83a.png)

srcCode not the true source， so the coverage will be incorrect

the App.vue just has 21 line， but the coverage has 56

![image](https://user-images.githubusercontent.com/70792885/151481826-49d29342-5492-4d78-b6cd-bcb4b1acc345.png)

**Comment by iFaxity** [comment] 2022-02-09 23:53
Hi @songjiachao, the Istanbul instrumenter should handle the inputSourceMap from the source code (srcCode). Therefore it doesn't need the true source as it works with the original source from the sourceMap.

I'll look into it and see what is causing the instrumenter to not handle the sourceMap correctly.

**Comment by songjiachao** [comment] 2022-02-11 03:34
Thank you very much ! 
I  alse created a discussion in vite repository .you can have a look.
[https://github.com/vitejs/vite/discussions/6831](https://github.com/vitejs/vite/discussions/6831)

**Comment by songjiachao** [comment] 2022-05-31 08:24
Is there a solution to resolve this problem?

**Comment by iFaxity** [comment] 2022-06-01 21:14
Hey @songjiachao, not yet.

I don't really know the root cause of this. Could be due to how Vue's SFC compiler mangles the sourcemap, istanbulbabel reading the sourcemap, babel within the istanbul instrumenter, etc.. As this plugin doesn't really meddle with the sourcemap at all.

**Comment by iFaxity** [comment] 2022-06-01 21:15
Due to there being many different factors and no real way for me to debug this.

This makes finding a fix for general sourcemap errors really hard.

**Comment by iFaxity** [comment] 2023-05-03 12:05
Closing this as there has not been any progress on this for almost a year now.

**Closed by iFaxity** 2023-05-03 12:05 UTC
Labels: bug
