### ISSUE TITLE
Plugin is not instrumenting the vite code need help !!!

### ISSUE THREAD

**Issue by harishraut-Aut** [iFaxity/vite-plugin-istanbul#158] opened 2023-11-16 05:30 UTC
Im using the vite-react application 

i installed this plugin 
and made all the changes as per the documentation 

this is my vite.config.ts file

![image](https://github.com/iFaxity/vite-plugin-istanbul/assets/74245017/56d48aaf-04cc-4ed7-a5f2-348eba03af7e)

This is the message i am seeing when i run the dev server from client directory 

![image](https://github.com/iFaxity/vite-plugin-istanbul/assets/74245017/d4ef866a-daaf-4fac-bdd3-5fe07e60d183)

After server is started i should see the window coverage object but im not able to see it also the code is not instrumented i need help 

![image](https://github.com/iFaxity/vite-plugin-istanbul/assets/74245017/eebd47b2-07dc-4dbe-a3de-6fa2192c330f)

**Comment by iFaxity** [comment] 2024-02-17 23:12
Hi @harishraut-Aut,

I cannot really know for sure what's going on without a reproduction of the issue.
Please submit a repository with an example project where i can debug the issue.
As there are a bunch of different tools involved in your setup the issue might not really be related to the plugin.

Especially since the Vite dev server failed and indicated something about the babel plugin before it crashed.

**Comment by iFaxity** [comment] 2024-02-17 23:21
Closing until @harishraut-Aut opens the issue again.

**Closed by iFaxity** 2024-02-17 23:21 UTC
Labels: question
