### ISSUE TITLE
vue3  coverage file path incorrect

### ISSUE THREAD

**Issue by qiguoqiang** [iFaxity/vite-plugin-istanbul#43] opened 2022-06-10 02:17 UTC
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/12483064/172976840-46001f1b-2c4b-423b-8a6b-6725b0d7c198.png">

Why do two identical file paths exist and the second path is carried after it “?vue&type=script&lang.ts“

The file Path is correct when I use forceBuildInstrument=false. When I use forceBuildInstrument=true, the filepath appears as shown in the figure above. It looks like there is a problem with filepath in Build mode

**Comment by iFaxity** [comment] 2022-06-10 22:18
Hello, the same is showing in serve mode and is how Vite specifically transforms Vue code SFC components.

For example look at the comment here: https://github.com/vitejs/vite/blob/f59adf8ebe06cf1df827a813ccea6cf6ceb127dd/packages/plugin-vue-jsx/src/index.ts#L88. In other words this is not a bug but rather a feature of how Vite instruments Vue SFC files.

Why the paths are correct when forceBuildInstrument=false then the plugin should not instrument at all in build mode and the filepaths should not show at all in window.__coverage__.

**Comment by iFaxity** [comment] 2023-05-03 12:09
This has been resolved in a newer version, v4.0.0.

**Closed by iFaxity** 2023-05-03 12:09 UTC
